# Generated by Django 5.2.5 on 2025-08-29 05:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
