# Generated by Django 5.2.5 on 2025-08-29 05:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_menuitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="logo_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="logo_image"
            ),
        ),
    ]
