# Generated by Django 5.2.5 on 2025-08-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_qrcode_image_alter_qrcode_logo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items"),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_logos"),
        ),
    ]
