# Generated by Django 5.2.5 on 2025-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0009_dailyrevenue_activitylog_visitorlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorlog",
            name="session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
