# Generated by Django 5.2.5 on 2025-08-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0010_alter_visitorlog_session_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["category"]},
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="visitorlog",
            name="visitor_type",
            field=models.CharField(
                choices=[
                    ("anonymous", "Anonymous Visitor"),
                    ("customer", "Customer"),
                    ("manager", "Manager"),
                ],
                default="anonymous",
                max_length=10,
            ),
        ),
    ]
