# Generated by Django 5.2.5 on 2025-08-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0011_alter_menuitem_options_category_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"]},
        ),
    ]
