# Generated by Django 5.2.5 on 2025-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0012_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
