# Generated by Django 5.2.5 on 2025-09-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0013_order_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitorlog",
            name="duration",
            field=models.FloatField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
    ]
