# Generated by Django 5.2.5 on 2025-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0014_alter_visitorlog_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="uuid",
            field=models.CharField(
                default="", editable=False, max_length=8, unique=True
            ),
        ),
    ]
